# Generated by Django 5.1.1 on 2024-10-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realisation',
            name='link',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
