# Generated by Django 5.1.1 on 2024-10-05 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_realisation_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiences',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/experiences/'),
        ),
        migrations.AlterField(
            model_name='realisation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/realisations'),
        ),
    ]
